const ActionTypes = {
    USERNAME: "USERNAME",
    SIGNUP: "SIGNUP",
    SIGNIN: "SIGNIN",
    SIGNOUT: "SIGNOUT",
    ERROR: 'ERROR', 
    SIGNUPERROR: 'SIGNUPERROR',
    REQUIREMENT: 'REQUIREMENT',
    GETDATA: 'GETDATA',
    GETKEYS: 'GETKEYS',
    GETNOGOS: 'GETNOGOS',
    GETUSERS: 'GETUSERS',    
}

export default ActionTypes;
